using Deucarian.TemplateGameMovementFps.Definitions;
using UnityEngine;

namespace Deucarian.TemplateGameMovementFps.Movement
{
    internal sealed class WallrunnerSettings
    {
        // Values are copied from the legacy serialized motor at its boundary.
        public float WalkSpeed { get; set; } = 7f;
        public float SprintSpeed { get; set; } = 10.5f;
        public float SlideSpeed { get; set; } = 14.5f;
        public float SlideDurationSeconds { get; set; } = 0.72f;
        public float AirborneSlideBufferSeconds { get; set; } = 0.22f;
        public float SlideEnterSpeedMultiplier { get; set; } = 1.18f;
        public float SlideJumpMinimumSpeedMultiplier { get; set; } = 1.2f;
        public float SlideJumpPeakSpeedMultiplier { get; set; } = 1.55f;
        public float SlideJumpSpeedCapMultiplier { get; set; } = 2.2f;
        public float SlideMinimumEntrySpeedFraction { get; set; } = 0.2f;
        public float SlideDragDelayFraction { get; set; } = 0.35f;
        public float SlideEntrySpeedDelayExponent { get; set; } = 1.45f;
        public float SlideDragRampExponent { get; set; } = 2.8f;
        public float SlideEntrySpeedDecayResistanceExponent { get; set; } = 1.15f;
        public float SlideSpeedDecayPerSecond { get; set; } = 1.6f;
        public float SlideDownhillSpeedGainPerSecond { get; set; } = 3.6f;
        public float SlideDownhillEnterSpeedMultiplier { get; set; } = 1.35f;
        public float SlideDownhillSpeedCapMultiplier { get; set; } = 4f;
        public float SlideUphillSpeedLossPerSecond { get; set; } = 5.2f;
        public float SlideSlopeEffectMinimumAngleDegrees { get; set; } = 20f;
        public float SlideGroundSnapDistance { get; set; } = 0.52f;
        public float SlideGroundSnapBreakAngleDegrees { get; set; } = 38f;
        public float SlideGroundSnapReleaseDropAngleDegrees { get; set; } = 45f;
        public float GroundAcceleration { get; set; } = 48f;
        public float GroundSnapDistance { get; set; } = 0.18f;
        public float GroundSnapBreakAngleDegrees { get; set; } = 38f;
        public float GroundSnapReleaseDropAngleDegrees { get; set; } = 45f;
        public float GroundSnapReleaseMinimumDrop { get; set; } = 0.04f;
        public float DownhillGroundStickExtraProbeDistance { get; set; } = 0.48f;
        public float DownhillGroundStickExtraLookAhead { get; set; } = 0.75f;
        public float DownhillGroundStickMinimumAngleDegrees { get; set; } = 3f;
        public float DownhillGroundStickFadeStartAngleDegrees { get; set; } = 24f;
        public float DownhillGroundStickFadeEndAngleDegrees { get; set; } = 56f;
        public float JumpVelocity { get; set; } = 8.3f;
        public int ExtraAirJumps { get; set; } = 1;
        public float AirAcceleration { get; set; } = 18f;
        public float Gravity { get; set; } = 24f;
        public float GroundContactProbeDistance { get; set; } = 0.12f;
        public float GroundContactRadiusMultiplier { get; set; } = 0.45f;
        public float StandableGroundMaxAngleDegrees { get; set; } = 60f;
        public float GroundedJumpGraceSeconds { get; set; } = 0.12f;
        public float JumpGroundLockoutSeconds { get; set; } = 0.14f;
        public bool MaxVelocityEnabled { get; set; }
        public float MaxVelocityMetersPerSecond { get; set; } = 36f;
        public bool MaxVelocityHardCap { get; set; } = true;
        public float MaxVelocitySoftPullPerSecond { get; set; } = 18f;
        public bool BunnyHopEnabled { get; set; } = true;
        public float BunnyHopLandingWindowSeconds { get; set; } = 0.16f;
        public float BunnyHopSteerStrength { get; set; } = 0.35f;
        public float BunnyHopSpeedMultiplier { get; set; } = 1.04f;
        public float WallrunSpeed { get; set; } = 12f;
        public float WallrunGravity { get; set; } = 4.8f;
        public float WallrunDurationSeconds { get; set; } = 1.45f;
        public float WallrunApexTime { get; set; } = 0.48f;
        public float WallrunApexSpeedMultiplier { get; set; } = 1.22f;
        public float WallrunPostApexRetention { get; set; } = 0.92f;
        public float WallrunLateDecelStart { get; set; } = 0.8f;
        public float WallrunLateDecelExponent { get; set; } = 3.2f;
        public float WallrunEndSpeedRetention { get; set; } = 0.42f;
        public float WallrunApexHeight { get; set; } = 1.35f;
        public float WallrunFatigueGravityMultiplier { get; set; } = 3.2f;
        public float WallrunMaxDownwardVelocity { get; set; } = 9f;
        public float WallJumpSpeedMultiplier { get; set; } = 1.42f;
        public float WallJumpTurnaroundSpeedMultiplier { get; set; } = 1.2f;
        public float WallJumpSpeedCapMultiplier { get; set; } = 2.45f;
        public float WallJumpMinimumSpeedFraction { get; set; } = 0.2f;
        public float WallJumpApexTimingWindow { get; set; } = 0.24f;
        public float WallJumpPeakTimingMultiplier { get; set; } = 1.24f;
        public float WallJumpVerticalVelocity { get; set; } = 5.6f;
        public float WallJumpLookWeight { get; set; } = 0.52f;
        public float WallJumpAwayWeight { get; set; } = 0.44f;
        public float WallJumpCarryWeight { get; set; } = 0.2f;
        public float WallJumpMinimumAwayDot { get; set; } = 0.38f;
        public float WallrunSameWallLockoutSeconds { get; set; } = 0.16f;
        public bool WallrunDetachReattachDelayEnabled { get; set; }
        public float WallrunDetachReattachDelaySeconds { get; set; } = 0.1f;
        public float WallrunReverseReentryDot { get; set; } = -0.25f;
        public float WallrunMaximumSurfaceTurnAngle { get; set; } = 60f;
        public float WallrunUpperProbeHeightFraction { get; set; } = 0.42f;
        public float WallrunTopFlattenProbeHeightFraction { get; set; } = 0.5f;
        public float WallrunTopUpwardVelocityMultiplier { get; set; } = 0.25f;
        public float WallrunCurvedSurfaceProbeForwardBias { get; set; } = 0.45f;
        public float WallrunHorizontalWallStickSpeed { get; set; } = 0f;
        public bool VerticalWallrunEnabled { get; set; } = true;
        public float VerticalWallrunLookMaxAngleDegrees { get; set; } = 26f;
        public float VerticalWallrunMinimumLookUpAngleDegrees { get; set; } = 10f;
        public float VerticalWallrunMoveMaxAngleDegrees { get; set; } = 40f;
        public float VerticalWallrunMinimumEntrySpeedFraction { get; set; } = 0.2f;
        public float VerticalWallrunUpSpeed { get; set; } = 9.2f;
        public float VerticalWallrunDurationSeconds { get; set; } = 0.9f;
        public float VerticalWallrunLateDecelStart { get; set; } = 0.55f;
        public float VerticalWallrunLateDecelExponent { get; set; } = 2.6f;
        public float VerticalWallrunEndSpeedRetention { get; set; } = 0.22f;
        public float VerticalWallrunWallStickSpeed { get; set; } = 2.2f;
        public VaultMode VaultMode { get; set; } = VaultMode.Hybrid;
        public bool VaultHoldAssistEnabled { get; set; } = true;
        public float MantleCheckDistance { get; set; } = 1.1f;
        public float MantleHeight { get; set; } = 2.35f;
        public float VaultFlowMaxHeightMeters { get; set; } = 1.45f;
        public float VaultMantleMaxHeightMeters { get; set; } = 2.35f;
        public float FlowVaultOverDistanceMeters { get; set; } = 1.45f;
        public float SafetyMantleOverDistanceMeters { get; set; } = 0.75f;
        public float FlowVaultBlendDurationSeconds { get; set; } = 0.08f;
        public float SafetyMantleBlendDurationSeconds { get; set; } = 0.22f;
        public float FlowVaultBaseSpeedMultiplier { get; set; } = 1.04f;
        public float FlowVaultPerfectSpeedMultiplier { get; set; } = 1.16f;
        public float SafetyMantleBaseSpeedMultiplier { get; set; } = 0.82f;
        public float SafetyMantlePerfectSpeedMultiplier { get; set; } = 1.04f;
        public float FlowVaultMinimumVerticalBoost { get; set; } = 0.22f;
        public float FlowVaultPerfectVerticalBoost { get; set; } = 0.42f;
        public float SafetyMantleMinimumVerticalBoost { get; set; } = 0.1f;
        public float SafetyMantlePerfectVerticalBoost { get; set; } = 0.26f;
        public float MantleVaultOverDistance { get; set; } = 1.25f;
        public float VaultMinimumSpeedFraction { get; set; } = 0.2f;
        public float VaultBaseSpeedMultiplier { get; set; } = 1.08f;
        public float VaultPerfectSpeedMultiplier { get; set; } = 1.35f;
        public float VaultMinimumVerticalBoost { get; set; } = 0.28f;
        public float VaultPerfectVerticalBoost { get; set; } = 0.58f;
        public float VaultBlendDurationSeconds { get; set; } = 0.12f;
        public float MantleMaximumWallNormalY { get; set; } = 0.22f;
        public float MantleMinimumTopNormalY { get; set; } = 0.55f;
        public float MantleMinimumApproachDot { get; set; } = 0.2f;
        public float SkinWidth { get; set; } = 0.04f;

        internal float MinimumGroundNormalY => Mathf.Cos(StandableGroundMaxAngleDegrees * Mathf.Deg2Rad);
    }
}
